### ISSUE TITLE
Unsure of how this is supposed to work

### ISSUE THREAD

**Issue by superfein** [davidwebca/custom-editor-sidebar-width#1]
First off, thanks @davidwebca for creating this plugin! Great idea!! I've downloaded the ZIP and extracted it in my plugins folder, but in Gutenberg the editor sidebar is not resizable. Can you perhaps give some explanation or a screenshot for how this plugin is supposed to work? I had assumed, by your description of the plugin, that I could drag the sidebar to make it larger. This doesn't seem to be an option/perhaps doesn't work for me. Maybe I'm not understanding?

Appreciate any guidance you could offer.

**Comment by davidwebca** [comment]
Hi! Thanks for trying it out. It's adding a button at the top of the Gutenberg editor (just like Yoast if you use that). Once you click on it, you'll have access to a range slider. I'll provide a screenshot later since I'm busy right now. But I'm definitely noting the drag idea, I totally went for the easiest solution to get it out quickly!

**Comment by davidwebca** [comment]
Here you go. I added a gif to show an example in the readme. If it still doesn't work, let me know! Otherwise you're free to close this issue and I'll check back on the drag idea later.

![Visual example](https://github.com/davidwebca/custom-editor-sidebar-width/raw/main/example.gif "Visual example or the plugin")

**Comment by superfein** [comment]
Thanks for taking the time to make the GIF and provide guidance on how to use it. For me, that button does not appear in the Gutenberg editor. I'm using the latest version of WP, using the Twenty Twenty-One theme, and Flywheel's Local dev environment on a Windows machine. The latest version of ACF is installed, but I doubt that matters. 

I looked in the console for errors while in the WP dashboard, and I've included a screenshot of the error messages. It appears the DIRECTORY_SEPARATOR isn't providing a forward slash separator. Or perhaps it's something else, but the asset URLs clearly indicate missing separators for the nested folders. 

![cesw-asset-load-error](https://user-images.githubusercontent.com/10688655/119890167-204d6300-bf55-11eb-8729-25cac2c6d8a9.png)

**Comment by superfein** [comment]
These two lines seem to be the problem:

```
$script_url = plugin_dir_url( __FILE__ ) . 'dist' . $ds . 'scripts' . $ds . 'app.js';
$script_vendor_url = plugin_dir_url( __FILE__ ) . 'dist' . $ds . 'vendor.js';
```

By replacing the `$ds` instances with a `'/'` the issue was resolved. Not sure why the DIRECTORY_SEPARATOR works fine with `plugin_dir_path` but not `plugin_dir_url`. Hope this helps.

**Comment by davidwebca** [comment]
I'm not sure why, but you're right anyway in a sense: I shouldn't be using directory separator for urls. 🤪  Are you on a non-unix server by any chance?

**Comment by superfein** [comment]
Yes, using Local by Flywheel on Windows.

**Comment by davidwebca** [comment]
Aaaah well that explains it. I just pushed a new version fixing the issue. Should be good to close!

**Comment by superfein** [comment]
![2ap1k1](https://user-images.githubusercontent.com/10688655/119893689-4c6ae300-bf59-11eb-808a-d7ecfa1f29c8.jpg)

Haha

**Comment by superfein** [comment]
Thanks @davidwebca!
