### ISSUE TITLE
WordPress 5.8

### ISSUE THREAD

**Issue by davideprevosto** [davidwebca/custom-editor-sidebar-width#3]
Unfortunately upgrading to WordPress 5.8 I am getting this errror: 

"wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets).

**Comment by davideprevosto** [comment]
Hello, it seems the previous issue was "true". Enabling your plugin with WordPress 5.8 we are getting that notice:

`"wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets)`

It happens into the Widget section `/wp-admin/widgets.php`.

It seems issue is relative to WP dependencies:

`<?php return array('dependencies' => array('lodash', 'wp-api', 'wp-components', 'wp-dom-ready', 'wp-edit-post', 'wp-element', 'wp-i18n', 'wp-plugins'), 'version' => 'd142cf1bbbf32cd8f9d758436da25e78');
`

For example, removing `wp-edit-post` the notice goes away, but obviously it breaks the whole things.

Thank you

**Comment by davidwebca** [comment]
Hi! I've been on vacation, I just noticed this. Mmm thanks, I'll look into it. Must be related to the fact that WordPress core enqueues some of these scripts now to render admin views like the new widgets area. I'll look into it!

**Comment by davidwebca** [comment]
To solve this for now is that I've simply enqueued the scripts and styles in the editor pages (posts and pages) only and not in the new widgets screen. I'd really like to have this work in the widgets too since the new sidebar can be cramped there as well, but it won't be possible for now since one of the react components needed lives in "wp-editor". I commented on the most relevant trac issue I could find to get a notification whenever there'll be a follow-up.  https://core.trac.wordpress.org/ticket/53664#comment:3

But for now you can update and it should remove the warning! I'd like to point out that lots of plugins will have this issue, most popularly Yoast SEO in its current version (should be fixed soon too).
